[package]
authors = ["吴双 <dualwu_tech@outlook.com>"]
edition = "2018"
name = "easy-fs-fuse"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
easy-fs = {path = "../easy-fs"}
rand = "0.8"
